#ifndef COLOR_GEN_H
#define COLOR_GEN_H
// Autogenerated, do not edit.

float3 Color_D60_D65(float3 c)
{
    const float3 c0 = { 000.97282726, -00.00071821, 000.00293641 };
    const float3 c1 = { -00.00143811, 000.97380459, -00.00513566 };
    const float3 c2 = { 000.01311909, 000.00408883, 001.05158913 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_D65_D60(float3 c)
{
    const float3 c0 = { 001.02797151, 000.00077021, -00.00286672 };
    const float3 c1 = { 000.00145030, 001.02688038, 000.00501085 };
    const float3 c2 = { -00.01282999, -00.00400242, 000.95095807 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_XYZ(float3 c)
{
    const float3 c0 = { 000.41239077, 000.21263900, 000.01933080 };
    const float3 c1 = { 000.35758433, 000.71516865, 000.11919472 };
    const float3 c2 = { 000.18048084, 000.07219233, 000.95053232 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_Rec709(float3 c)
{
    const float3 c0 = { 003.24097013, -00.96924371, 000.05563008 };
    const float3 c1 = { -01.53738332, 001.87596750, -00.20397684 };
    const float3 c2 = { -00.49861082, 000.04155510, 001.05697119 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_XYZ(float3 c)
{
    const float3 c0 = { 000.63695812, 000.26270023, 000.00000000 };
    const float3 c1 = { 000.14461692, 000.67799807, 000.02807269 };
    const float3 c2 = { 000.16888094, 000.05930171, 001.06098485 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_Rec2020(float3 c)
{
    const float3 c0 = { 001.71665096, -00.66668433, 000.01763985 };
    const float3 c1 = { -00.35567081, 001.61648130, -00.04277061 };
    const float3 c2 = { -00.25336623, 000.01576854, 000.94210327 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_XYZ(float3 c)
{
    const float3 c0 = { 000.95255244, 000.34396645, 000.00000000 };
    const float3 c1 = { 000.00000000, 000.72816604, 000.00000000 };
    const float3 c2 = { 000.00009368, -00.07213254, 001.00882506 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_AP0(float3 c)
{
    const float3 c0 = { 001.04981089, -00.49590302, 000.00000000 };
    const float3 c1 = { -00.00000000, 001.37331307, -00.00000000 };
    const float3 c2 = { -00.00009748, 000.09824004, 000.99125206 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_XYZ(float3 c)
{
    const float3 c0 = { 000.66245425, 000.27222878, -00.00557469 };
    const float3 c1 = { 000.13400421, 000.67408168, 000.00406073 };
    const float3 c2 = { 000.15618765, 000.05368950, 001.01033890 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_AP1(float3 c)
{
    const float3 c0 = { 001.64102328, -00.66366309, 000.01172196 };
    const float3 c1 = { -00.32480329, 001.61533189, -00.00828445 };
    const float3 c2 = { -00.23642468, 000.01675636, 000.98839509 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_XYZ_D60(float3 c)
{
    const float3 c0 = { 000.42398635, 000.21859509, 000.01826607 };
    const float3 c1 = { 000.36709443, 000.73419100, 000.11590769 };
    const float3 c2 = { 000.17343853, 000.07046746, 000.90376073 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_XYZ_D60(float3 c)
{
    const float3 c0 = { 000.65515578, 000.27025232, -00.00050963 };
    const float3 c1 = { 000.14928520, 000.69622195, 000.02967872 };
    const float3 c2 = { 000.16007836, 000.05677932, 001.00876522 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_XYZ_D65(float3 c)
{
    const float3 c0 = { 000.92617434, 000.33427197, 000.00103058 };
    const float3 c1 = { -00.00104718, 000.70909142, -00.00373961 };
    const float3 c2 = { 000.01342973, -00.06611815, 001.06124020 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_XYZ_D65(float3 c)
{
    const float3 c0 = { 000.64398891, 000.26459908, -00.00531512 };
    const float3 c1 = { 000.12944680, 000.65634423, 000.00120185 };
    const float3 c2 = { 000.16512112, 000.05630201, 001.06264424 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_Rec2020(float3 c)
{
    const float3 c0 = { 000.62740374, 000.06909731, 000.01639142 };
    const float3 c1 = { 000.32928297, 000.91954046, 000.08801328 };
    const float3 c2 = { 000.04331309, 000.01136230, 000.89559555 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_Rec709(float3 c)
{
    const float3 c0 = { 001.66049135, -00.12455052, -00.01815073 };
    const float3 c1 = { -00.58764112, 001.13289988, -00.10057884 };
    const float3 c2 = { -00.07284993, -00.00834937, 001.11872911 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_AP0(float3 c)
{
    const float3 c0 = { 000.44510370, 000.09173784, 000.01810628 };
    const float3 c1 = { 000.38536844, 000.83761758, 000.11489374 };
    const float3 c2 = { 000.18198957, 000.09955067, 000.89585471 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_Rec709(float3 c)
{
    const float3 c0 = { 002.48728561, -00.27056241, -00.01557129 };
    const float3 c1 = { -01.09167457, 001.33109200, -00.14864914 };
    const float3 c2 = { -00.38397157, -00.09295224, 001.13593400 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_AP1(float3 c)
{
    const float3 c0 = { 000.62045252, 000.07202560, 000.02121311 };
    const float3 c1 = { 000.33653942, 000.94427723, 000.11278329 };
    const float3 c2 = { 000.04805727, 000.01386732, 000.89472198 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_Rec709(float3 c)
{
    const float3 c0 = { 001.68300891, -00.12802380, -00.02376486 };
    const float3 c1 = { -00.59011865, 001.10586488, -00.12540756 };
    const float3 c2 = { -00.08125103, -00.01026359, 001.12088573 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_AP0(float3 c)
{
    const float3 c0 = { 000.68778974, 000.04619727, -00.00050517 };
    const float3 c1 = { 000.15671833, 000.88501531, 000.02941909 };
    const float3 c2 = { 000.16795367, 000.09769358, 000.99994063 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_Rec2020(float3 c)
{
    const float3 c0 = { 001.47076619, -00.07710528, 000.00301148 };
    const float3 c1 = { -00.25305325, 001.14687216, -00.03386985 };
    const float3 c2 = { -00.22231197, -00.09909794, 001.00286269 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_AP1(float3 c)
{
    const float3 c0 = { 000.98746759, 000.00173593, 000.00493710 };
    const float3 c1 = { 000.01182853, 001.02605176, 000.02531640 };
    const float3 c2 = { 000.00575322, 000.00238259, 000.99846458 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_Rec2020(float3 c)
{
    const float3 c0 = { 001.01274061, -00.00170165, -00.00496459 };
    const float3 c1 = { -00.01153201, 000.97468698, -00.02465655 };
    const float3 c2 = { -00.00580782, -00.00231617, 001.00162518 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};

#endif // COLOR_GEN_H

