#ifndef COLOR_GEN_H
#define COLOR_GEN_H
// Autogenerated, do not edit.

float3 Color_D60_D65(float3 c)
{
    const float3 c0 = { 000.97282726, -00.00071821, 000.00293641 };
    const float3 c1 = { -00.00143811, 000.97380459, -00.00513566 };
    const float3 c2 = { 000.01311909, 000.00408883, 001.05158913 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_D65_D60(float3 c)
{
    const float3 c0 = { 001.02797151, 000.00077021, -00.00286672 };
    const float3 c1 = { 000.00145030, 001.02688038, 000.00501085 };
    const float3 c2 = { -00.01282999, -00.00400242, 000.95095807 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_XYZ(float3 c)
{
    const float3 c0 = { 000.41239074, 000.21263897, 000.01933080 };
    const float3 c1 = { 000.35758430, 000.71516860, 000.11919472 };
    const float3 c2 = { 000.18048079, 000.07219231, 000.95053214 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_Rec709(float3 c)
{
    const float3 c0 = { 003.24097013, -00.96924371, 000.05563009 };
    const float3 c1 = { -01.53738332, 001.87596762, -00.20397688 };
    const float3 c2 = { -00.49861085, 000.04155508, 001.05697143 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_XYZ(float3 c)
{
    const float3 c0 = { 000.63695812, 000.26270023, 000.00000000 };
    const float3 c1 = { 000.14461692, 000.67799807, 000.02807269 };
    const float3 c2 = { 000.16888094, 000.05930171, 001.06098485 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_Rec2020(float3 c)
{
    const float3 c0 = { 001.71665096, -00.66668433, 000.01763985 };
    const float3 c1 = { -00.35567081, 001.61648130, -00.04277061 };
    const float3 c2 = { -00.25336623, 000.01576854, 000.94210327 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_XYZ(float3 c)
{
    const float3 c0 = { 000.95255244, 000.34396645, 000.00000000 };
    const float3 c1 = { 000.00000000, 000.72816604, 000.00000000 };
    const float3 c2 = { 000.00009368, -00.07213254, 001.00882506 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_AP0(float3 c)
{
    const float3 c0 = { 001.04981089, -00.49590302, 000.00000000 };
    const float3 c1 = { 000.00000000, 001.37331307, 000.00000000 };
    const float3 c2 = { -00.00009748, 000.09824004, 000.99125206 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_XYZ(float3 c)
{
    const float3 c0 = { 000.66245425, 000.27222878, -00.00557469 };
    const float3 c1 = { 000.13400422, 000.67408180, 000.00406073 };
    const float3 c2 = { 000.15618768, 000.05368951, 001.01033902 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_XYZ_AP1(float3 c)
{
    const float3 c0 = { 001.64102340, -00.66366303, 000.01172196 };
    const float3 c1 = { -00.32480329, 001.61533177, -00.00828445 };
    const float3 c2 = { -00.23642471, 000.01675637, 000.98839504 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_XYZ_D60(float3 c)
{
    const float3 c0 = { 000.42398632, 000.21859506, 000.01826607 };
    const float3 c1 = { 000.36709440, 000.73419094, 000.11590768 };
    const float3 c2 = { 000.17343849, 000.07046744, 000.90376061 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_XYZ_D60(float3 c)
{
    const float3 c0 = { 000.65515578, 000.27025232, -00.00050963 };
    const float3 c1 = { 000.14928520, 000.69622195, 000.02967872 };
    const float3 c2 = { 000.16007836, 000.05677932, 001.00876522 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_XYZ_D65(float3 c)
{
    const float3 c0 = { 000.92617434, 000.33427197, 000.00103058 };
    const float3 c1 = { -00.00104718, 000.70909142, -00.00373961 };
    const float3 c2 = { 000.01342973, -00.06611815, 001.06124020 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_XYZ_D65(float3 c)
{
    const float3 c0 = { 000.64398891, 000.26459908, -00.00531512 };
    const float3 c1 = { 000.12944682, 000.65634429, 000.00120185 };
    const float3 c2 = { 000.16512115, 000.05630201, 001.06264436 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_Rec2020(float3 c)
{
    const float3 c0 = { 000.62740374, 000.06909731, 000.01639142 };
    const float3 c1 = { 000.32928294, 000.91954035, 000.08801328 };
    const float3 c2 = { 000.04331309, 000.01136230, 000.89559537 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_Rec709(float3 c)
{
    const float3 c0 = { 001.66049135, -00.12455049, -00.01815074 };
    const float3 c1 = { -00.58764112, 001.13290000, -00.10057885 };
    const float3 c2 = { -00.07284999, -00.00834939, 001.11872935 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_AP0(float3 c)
{
    const float3 c0 = { 000.44510368, 000.09173781, 000.01810628 };
    const float3 c1 = { 000.38536841, 000.83761752, 000.11489373 };
    const float3 c2 = { 000.18198952, 000.09955066, 000.89585459 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_Rec709(float3 c)
{
    const float3 c0 = { 002.48728561, -00.27056241, -00.01557130 };
    const float3 c1 = { -01.09167457, 001.33109200, -00.14864917 };
    const float3 c2 = { -00.38397163, -00.09295227, 001.13593423 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec709_AP1(float3 c)
{
    const float3 c0 = { 000.62045252, 000.07202557, 000.02121310 };
    const float3 c1 = { 000.33653942, 000.94427717, 000.11278328 };
    const float3 c2 = { 000.04805723, 000.01386734, 000.89472181 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_Rec709(float3 c)
{
    const float3 c0 = { 001.68300891, -00.12802377, -00.02376487 };
    const float3 c1 = { -00.59011877, 001.10586512, -00.12540761 };
    const float3 c2 = { -00.08125108, -00.01026362, 001.12088609 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_AP0(float3 c)
{
    const float3 c0 = { 000.68778974, 000.04619727, -00.00050517 };
    const float3 c1 = { 000.15671833, 000.88501531, 000.02941909 };
    const float3 c2 = { 000.16795367, 000.09769358, 000.99994063 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP0_Rec2020(float3 c)
{
    const float3 c0 = { 001.47076619, -00.07710528, 000.00301148 };
    const float3 c1 = { -00.25305325, 001.14687216, -00.03386985 };
    const float3 c2 = { -00.22231197, -00.09909794, 001.00286269 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_Rec2020_AP1(float3 c)
{
    const float3 c0 = { 000.98746759, 000.00173593, 000.00493710 };
    const float3 c1 = { 000.01182854, 001.02605164, 000.02531639 };
    const float3 c2 = { 000.00575319, 000.00238260, 000.99846452 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};
float3 Color_AP1_Rec2020(float3 c)
{
    const float3 c0 = { 001.01274061, -00.00170165, -00.00496459 };
    const float3 c1 = { -00.01153199, 000.97468710, -00.02465655 };
    const float3 c2 = { -00.00580782, -00.00231619, 001.00162530 };
    return c0 * c.x + c1 * c.y + c2 * c.z;
};

#endif // COLOR_GEN_H

