#pragma once
// Autogenerated, do not edit.
#include "math/float4_funcs.h"

PIM_C_BEGIN

pim_inline float4 VEC_CALL Color_D60_D65(float4 c)
{
    const float4 c0 = { 000.97282726f, -00.00071821f, 000.00293641f };
    const float4 c1 = { -00.00143811f, 000.97380459f, -00.00513566f };
    const float4 c2 = { 000.01311909f, 000.00408883f, 001.05158913f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_D65_D60(float4 c)
{
    const float4 c0 = { 001.02797151f, 000.00077021f, -00.00286672f };
    const float4 c1 = { 000.00145030f, 001.02688038f, 000.00501085f };
    const float4 c2 = { -00.01282999f, -00.00400242f, 000.95095807f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec709_XYZ(float4 c)
{
    const float4 c0 = { 000.41239074f, 000.21263897f, 000.01933080f };
    const float4 c1 = { 000.35758430f, 000.71516860f, 000.11919472f };
    const float4 c2 = { 000.18048079f, 000.07219231f, 000.95053214f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_XYZ_Rec709(float4 c)
{
    const float4 c0 = { 003.24097013f, -00.96924371f, 000.05563009f };
    const float4 c1 = { -01.53738332f, 001.87596762f, -00.20397688f };
    const float4 c2 = { -00.49861085f, 000.04155508f, 001.05697143f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec2020_XYZ(float4 c)
{
    const float4 c0 = { 000.63695812f, 000.26270023f, 000.00000000f };
    const float4 c1 = { 000.14461692f, 000.67799807f, 000.02807269f };
    const float4 c2 = { 000.16888094f, 000.05930171f, 001.06098485f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_XYZ_Rec2020(float4 c)
{
    const float4 c0 = { 001.71665096f, -00.66668433f, 000.01763985f };
    const float4 c1 = { -00.35567081f, 001.61648130f, -00.04277061f };
    const float4 c2 = { -00.25336623f, 000.01576854f, 000.94210327f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP0_XYZ(float4 c)
{
    const float4 c0 = { 000.95255244f, 000.34396645f, 000.00000000f };
    const float4 c1 = { 000.00000000f, 000.72816604f, 000.00000000f };
    const float4 c2 = { 000.00009368f, -00.07213254f, 001.00882506f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_XYZ_AP0(float4 c)
{
    const float4 c0 = { 001.04981089f, -00.49590302f, 000.00000000f };
    const float4 c1 = { 000.00000000f, 001.37331307f, 000.00000000f };
    const float4 c2 = { -00.00009748f, 000.09824004f, 000.99125206f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP1_XYZ(float4 c)
{
    const float4 c0 = { 000.66245425f, 000.27222878f, -00.00557469f };
    const float4 c1 = { 000.13400422f, 000.67408180f, 000.00406073f };
    const float4 c2 = { 000.15618768f, 000.05368951f, 001.01033902f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_XYZ_AP1(float4 c)
{
    const float4 c0 = { 001.64102340f, -00.66366303f, 000.01172196f };
    const float4 c1 = { -00.32480329f, 001.61533177f, -00.00828445f };
    const float4 c2 = { -00.23642471f, 000.01675637f, 000.98839504f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec709_XYZ_D60(float4 c)
{
    const float4 c0 = { 000.42398632f, 000.21859506f, 000.01826607f };
    const float4 c1 = { 000.36709440f, 000.73419094f, 000.11590768f };
    const float4 c2 = { 000.17343849f, 000.07046744f, 000.90376061f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec2020_XYZ_D60(float4 c)
{
    const float4 c0 = { 000.65515578f, 000.27025232f, -00.00050963f };
    const float4 c1 = { 000.14928520f, 000.69622195f, 000.02967872f };
    const float4 c2 = { 000.16007836f, 000.05677932f, 001.00876522f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP0_XYZ_D65(float4 c)
{
    const float4 c0 = { 000.92617434f, 000.33427197f, 000.00103058f };
    const float4 c1 = { -00.00104718f, 000.70909142f, -00.00373961f };
    const float4 c2 = { 000.01342973f, -00.06611815f, 001.06124020f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP1_XYZ_D65(float4 c)
{
    const float4 c0 = { 000.64398891f, 000.26459908f, -00.00531512f };
    const float4 c1 = { 000.12944682f, 000.65634429f, 000.00120185f };
    const float4 c2 = { 000.16512115f, 000.05630201f, 001.06264436f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec709_Rec2020(float4 c)
{
    const float4 c0 = { 000.62740374f, 000.06909731f, 000.01639142f };
    const float4 c1 = { 000.32928294f, 000.91954035f, 000.08801328f };
    const float4 c2 = { 000.04331309f, 000.01136230f, 000.89559537f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec2020_Rec709(float4 c)
{
    const float4 c0 = { 001.66049135f, -00.12455049f, -00.01815074f };
    const float4 c1 = { -00.58764112f, 001.13290000f, -00.10057885f };
    const float4 c2 = { -00.07284999f, -00.00834939f, 001.11872935f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec709_AP0(float4 c)
{
    const float4 c0 = { 000.44510368f, 000.09173781f, 000.01810628f };
    const float4 c1 = { 000.38536841f, 000.83761752f, 000.11489373f };
    const float4 c2 = { 000.18198952f, 000.09955066f, 000.89585459f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP0_Rec709(float4 c)
{
    const float4 c0 = { 002.48728561f, -00.27056241f, -00.01557130f };
    const float4 c1 = { -01.09167457f, 001.33109200f, -00.14864917f };
    const float4 c2 = { -00.38397163f, -00.09295227f, 001.13593423f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec709_AP1(float4 c)
{
    const float4 c0 = { 000.62045252f, 000.07202557f, 000.02121310f };
    const float4 c1 = { 000.33653942f, 000.94427717f, 000.11278328f };
    const float4 c2 = { 000.04805723f, 000.01386734f, 000.89472181f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP1_Rec709(float4 c)
{
    const float4 c0 = { 001.68300891f, -00.12802377f, -00.02376487f };
    const float4 c1 = { -00.59011877f, 001.10586512f, -00.12540761f };
    const float4 c2 = { -00.08125108f, -00.01026362f, 001.12088609f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec2020_AP0(float4 c)
{
    const float4 c0 = { 000.68778974f, 000.04619727f, -00.00050517f };
    const float4 c1 = { 000.15671833f, 000.88501531f, 000.02941909f };
    const float4 c2 = { 000.16795367f, 000.09769358f, 000.99994063f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP0_Rec2020(float4 c)
{
    const float4 c0 = { 001.47076619f, -00.07710528f, 000.00301148f };
    const float4 c1 = { -00.25305325f, 001.14687216f, -00.03386985f };
    const float4 c2 = { -00.22231197f, -00.09909794f, 001.00286269f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_Rec2020_AP1(float4 c)
{
    const float4 c0 = { 000.98746759f, 000.00173593f, 000.00493710f };
    const float4 c1 = { 000.01182854f, 001.02605164f, 000.02531639f };
    const float4 c2 = { 000.00575319f, 000.00238260f, 000.99846452f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};
pim_inline float4 VEC_CALL Color_AP1_Rec2020(float4 c)
{
    const float4 c0 = { 001.01274061f, -00.00170165f, -00.00496459f };
    const float4 c1 = { -00.01153199f, 000.97468710f, -00.02465655f };
    const float4 c2 = { -00.00580782f, -00.00231619f, 001.00162530f };
    return f4_add(f4_add(f4_mulvs(c0, c.x), f4_mulvs(c1, c.y)), f4_mulvs(c2, c.z));
};

PIM_C_END

